### Users - Register
POST http://localhost:3002/auth/register
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "username": "juanperez",
  "email": "juan@email.com",
  "password": "1234",
  "empresa": "Vial Jaime"
}

### Users - Login
POST http://localhost:3002/auth/login
Content-Type: application/json

{
  "username": "juanperez",
  "password": "1234"
}